name: PRValidator

on:
  pull_request_review:
    branches: 
      - develop

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild clean test -project SketchBook.xcodeproj -scheme SketchBook -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
          destination: 'platform=iOS Simulator,OS=13.1,name=iPhone 11'
